import greenmap from "../../assets/green-kauai.png";
export const ClickableMap = () => (
  <>
    <img
      className="home-map"
      alt="clickable map"
      src={greenmap}
      useMap="#image_map"
    />
    <map name="image_map">
      <area
        target="_self"
        alt="kona"
        title="kona"
        href="http://localhost:3000/kona"
        coords="423,48,105"
        shape="circle"
      />
      <area
        target="_self"
        alt="halelea"
        title="halelea"
        href="http://localhost:3000/halelea"
        coords="555,-100,59"
        shape="circle"
      />
      <area
        target="_self"
        alt="napali"
        title="napali"
        href="http://localhost:3000/napali"
        coords="443,-123,44"
        shape="circle"
      />
      <area
        target="_self"
        alt="koolau"
        title="koolau"
        href="http://localhost:3000/koolau"
        coords="688,-107,40"
        shape="circle"
      />
      <area
        target="_self"
        alt="puna"
        title="puna"
        href="http://localhost:3000/puna"
        coords="662,30,73"
        shape="circle"
      />
      <area
        target="_self"
        alt="kona2"
        title="kona2"
        href="http://localhost:3000/kona"
        coords="534,145,41"
        shape="circle"
      />
      <area
        target="_self"
        alt="kona3"
        title="kona3"
        href="http://localhost:3000/kona"
        coords="605,152,23"
        shape="circle"
      />
      <area
        target="_self"
        alt="niihau"
        title="niihau"
        href="http://localhost:3000/niihau"
        coords="99,104,113"
        shape="circle"
      />
    </map>
  </>
);
